src/EoManager/EoManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('supervisor.urls', namespace='supervisor')),
]

src/EoManager/supervisor/urls.py
from django.urls import path
from . import views


app_name = 'supervisor'

urlpatterns = [
    path('', views.tickets_list, name='tickets_list'),
    path('tickets/get/', views.fetch_tickets_list, name='fetch_tickets_list'),
    path('ticket/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('ticket/<int:id>/history/', views.fetch_ticket_history, name='fetch_ticket_history'),
    path('windows/', views.windows_list, name='windows_list'),
    path('windows/get/', views.fetch_windows_list, name='fetch_windows_list'),
    path('prerecord-free/', views.free_time_tickets_list, name='free_time_tickets_list'),
    path('prerecord-free/get/', 
         views.fetch_free_time_tickets_list, 
         name='fetch_free_time_tickets_list'
         ),
]

src/EoManager/supervisor/models.py
from django.db import models
from django.contrib.auth.models import User


class Division(models.Model):
    name = models.CharField(max_length=250, verbose_name='Название подразделения', unique=True)
    division_id = models.IntegerField(verbose_name='ID подразделения в системе Супервизор', unique=True)
    count_windows = models.PositiveIntegerField(verbose_name='Количество окон', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'
        indexes = [models.Index(fields=['name'])]
        ordering = ['name']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь',null=True, blank=True)
    full_name = models.CharField(max_length=500, verbose_name='ФИО пользователя')
    divisions = models.ManyToManyField(Division, verbose_name='Подразделения')
    photo_base64 = models.TextField(verbose_name='Фото профиля в base64', null=True, blank=True)
    eo_database_username = models.CharField(max_length=100, null=True, blank=True,
                                            verbose_name='Имя пользователя в системе ЭО')
    eo_database_id = models.IntegerField(null=True, blank=True, unique=True,
                                         verbose_name='ID пользователя в системе ЭО')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'
        indexes = [models.Index(fields=['full_name'])]
        ordering = ['full_name']

src/EoManager/supervisor/services/models/tickets_list.py
import time
from os.path import split

from pydantic import BaseModel, field_validator
from supervisor.services.encoding.ticket_status import ticket_statuses


class Service(BaseModel):
    id: int  # id услуги
    name: str  # название услуги
    prefix: str  # префикс услуги


class OperatorWindow(BaseModel):
    id: int  # id окна
    name: str  # номер окна


class Specialist(BaseModel):
    id: int
    lastname: str
    firstname: str
    middlename: str
    employeestate: str = None  # статус сотрудника в виде кода
    operatorwindow: OperatorWindow = None


class Ticket(BaseModel):
    id: int  # id талона
    ticketnumber: int  # порядковый номер талона
    ticketcode: str  # номер талона, например, РП3
    recordstate: dict  # статус талона в виде кода
    recorddate: str  # дата на который день запись в формате yyyy-mm-dd
    recordtime: str = None  # время на которое сделана запись в формате hh:mm:ss
    createdate: int  # дата когда был создан талон
    statedate: int  # ???
    fio: str = None  # ФИО заявителя
    phone: str = None  # телефон заявителя
    email: str = None  # email заявителя
    servicegroup: Service  # услуга на которую выдан талон
    isprerecord: bool  # true в случае предварительной записи, false в случае текущей
    prerecordEmployee: Specialist = None  # сотрудник на которого прикрепилась предварительная запись (только ПЗ)
    queueDate: str  # время записи в формате dd.mm.yyyy hh:mm (ПЗ на какое время) (ТЗ когда талон создан)
    actualDate: str = None  # фактические дата и время вызова на приём в формате dd.mm.yyyy hh:mm
    normative: str = ''  # время норматива по оказанию услуги
    actualServingTime: str = ''  # время обслуживания
    creationDate: str
    waitTime: dict = {'wait': '0 мин. 0 сек.', 'status': 'green'}  # время ожидания заявителя в очереди в формате
    waitTimeExpired: bool = False
    recordtimeString: str = None
    employee: Specialist = None
    appointmentWaitThreshold: str = None # Приоритет талона

    @field_validator('queueDate', mode='before')
    @classmethod
    def transform_queueDate(cls, raw: str) -> str:
        return raw.split()[1]

    @field_validator('recordstate', mode='before')
    @classmethod
    def encoding_status(cls, status: str) -> dict:
        return ticket_statuses.get_dict(db_name=status)

    @field_validator('actualServingTime', mode='before')
    @classmethod
    def convert_actualServingTime(cls, serving_time: int) -> str:
        return time.strftime('%H:%M:%S', time.gmtime(serving_time / 1000))

    @field_validator('normative', mode='before')
    @classmethod
    def convert_normative(cls, normative_int: int) -> str:
        return time.strftime('%H:%M:%S', time.gmtime(normative_int / 1000))

    @field_validator('waitTime', mode='before')
    @classmethod
    def convert_wait_time(cls, wait_time: str) -> dict:
        h, m, s = map(int, wait_time.split(':'))
        m = h * 60 if h > 0 else m
        status = 'green'
        if m >= 10:
            status = 'yellow'
        if m >= 15:
            status = 'red'
        return {'wait': f'{m} мин. {s} сек.', 'status': status}


class Content(BaseModel):
    content: list[Ticket]

    @field_validator('content', mode='after')
    @classmethod
    def sorted_content(cls, content: list) -> list:
        return sorted(content, key=lambda ticket: ticket.queueDate)

src/EoManager/supervisor/views.py
import datetime

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden
from django.views.decorators.http import require_GET, require_POST
from django.contrib.auth.decorators import login_required

from supervisor.services.eoapi import TicketsManager, RequestTicketsListParams
from supervisor.services.encoding.ticket_status import ticket_statuses
from supervisor.models import Division, Profile


@login_required
@require_GET
def tickets_list(request: HttpRequest) -> HttpResponse:
    """Страница со списком талонов"""
    divisions = request.user.profile.divisions.values()
    return render(
        request, 'supervisor/tickets_list.html', context={
            'statuses': ticket_statuses.get_all(),
            'date': datetime.date.today().strftime('%Y-%m-%d'),
            'divisions': divisions
        }
    )


@login_required
# @require_GET
def fetch_tickets_list(request: HttpRequest) -> HttpResponse | HttpResponseForbidden:
    """JSON со списком талонов"""
    api = TicketsManager()

    params = RequestTicketsListParams()
    params.set_request_get_params(request)

    result = api.get_tickets_list(params=params)
    if RequestTicketsListParams.check_division_access(request.user, params.division_id):
        return HttpResponse(result)
    return HttpResponseForbidden(
        f'Ошибка доступа. Пользователь {request.user.username} не добавлен в подразделение с ID: {params.division_id}'
    )


@login_required
def ticket_detail(request: HttpRequest, ticket_id: int) -> HttpResponse:
    """Страница с детальной информацией о талоне и его истории"""
    print('GET', request)
    context = {'ticket_id': ticket_id}
    return render(request, 'supervisor/ticket_detail.html', context=context)


@login_required
@require_GET
def fetch_ticket_history(request: HttpRequest) -> str:
    """JSON с историей талона"""
    pass


@login_required
@require_GET
def windows_list(request: HttpRequest) -> HttpResponse:
    """Страница со списком окон"""
    return render(request, 'supervisor/windows_list.html')


@login_required
@require_GET
def fetch_windows_list(request: HttpRequest) -> str:
    """JSON со списком окон"""
    pass


@login_required
@require_GET
def free_time_tickets_list(request: HttpRequest) -> HttpResponse:
    """Страница со списком доступных для ПЗ услуг"""
    return render(request, 'supervisor/free_time_tickets_list.html')


@login_required
@require_GET
def fetch_free_time_tickets_list(request: HttpRequest) -> str:
    """JSON со списком доступных для ПЗ услуг"""
    pass

src/EoManager/templates/supervisor/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "styles/base.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">

    {% block head %}
    {% endblock head %}
</head>
<body>
<header>
    <ul>
        <li><a href="{% url "supervisor:tickets_list" %}">Талоны</a></li>
        <li><a href="{% url "supervisor:windows_list" %}">Окна</a></li>
        <li><a href="{% url "supervisor:free_time_tickets_list" %}">Доступ к ПЗ</a></li>
    </ul>
</header>
<main>
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
</main>
<footer>
    <p>Супервизор МФЦ</p>
    <p>2025</p>
</footer>

{% block is_rady %}
{% endblock is_rady %}

</body>
</html>

src/EoManager/templates/supervisor/free_time_tickets_list.html
{% extends "supervisor/base.html" %}

{% block content %}
    <h1>Доступные для предварительной записи услуги</h1>
    <div id="windows-list">
        <p>Таблица со списком доступных для предварительной записи услуг</p>
    </div>
{% endblock content %}

src/EoManager/templates/supervisor/ticket_detail.html
{% extends "supervisor/base.html" %}

{% block content %}
    <h1>Список талонов</h1>
    <div>
        <p>О талоне {{ ticket_id }}</p>
    </div>
    <div id="ticket-history">
        <p>Таблица с историей талона</p>
    </div>
{% endblock content %}

src/EoManager/templates/supervisor/tickets_list.html
{% extends "supervisor/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "styles/tickets-table.css" %}">
{% endblock head %}



{% block content %}
    <h1>Список талонов ЭО</h1>
    <div class='sticky-top'>
        <div class="filter">
            <form action="{% url "supervisor:fetch_tickets_list" %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="mt-1 col-2">
                        <label for="date"><b>Дата:</b></label>
                        <input type="date" name="date" id="date" class="form-control" value="{{ date }}">
                    </div>

                    <div class="mt-1 col-5">
                        <label for="division"><b>Подразделение:</b></label>

                        <select name="division" id="division" class="form-control">
                            {% for division in divisions %}
                            	<option value="{{ division.division_id }}">{{ division.name}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="mt-1 col-3">
                        <span><b>Тип записи:</b></span><br>

                        <input type="checkbox" name="prerecord" id="prerecord" class="form-check-input" checked>
                        <label for="prerecord" class="form-check-label">Предварительная запись</label>
                        <br>
                        <input type="checkbox" name="notprerecord" id="notprerecord" class="form-check-input" checked>
                        <label for="notprerecord" class="form-check-label">Текущая запись</label>
                    </div>
                    <div class="mt-4 col-2">
                        <a id="update-ticket-list-button" class="btn btn-primary">Обновить</a>
                    </div>
                </div>

                <div class="mt-1">
                    <span><b>Статус записи:</b></span><br>
                    {% for status in statuses %}
                        <input type="checkbox" name="{{ status.db_name }}" id="{{ status.db_name }}"
                               class="form-check-input statuses-form" {% if status.default %}checked{% endif %}>
                        <label for="{{ status.db_name }}" style="margin-right: 15px"
                               class="form-check-label">{{ status.frontend_name }}</label>
                    {% endfor %}
                </div>
            </form>
        </div>
        <div class="mt-1 search">
            <input type="text" id="searchInput" class="form-control" placeholder="Поиск..."/>
        </div>
    </div>
    <div id="tickets-list">
        <div>
            <table id="ticket-table">
                <thead>
                <tr>
                    <th style='width: 5%'>Время записи</th>
                    <th style='width: 5%'>Талон</th>
                    <th style='width: 14%'>Статус</th>
                    <th style='width: 10%'>Время ожидания</th>
                    <th style='width: 12%'>Тип записи</th>
                    <th style='width: 27%'>Услуга</th>
                    <th style='width: 14%'>Заявитель</th>
                    <th style="width: 12%">Специалист</th>
                </tr>
                </thead>
                <tbody class='ticket-list-body'>
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

{% block is_rady %}
    <script>
        let img_delete_url = '{% static "icons/delete.svg" %}'
        let img_redirect_url = '{% static "icons/redirect.svg" %}'
    </script>
    <script src="{% static 'scripts/tickets_list/load_tickets_list.js' %}"></script>
    <script>
        let load_tickets_list_url = "{% url "supervisor:fetch_tickets_list" %}";

        const csrftoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value

        document.addEventListener('DOMContentLoaded', (event) => {
            get_tickets_list();
        })
        document.getElementById('update-ticket-list-button').addEventListener('click', function (e) {
            get_tickets_list();
        })

        const searchInput = document.getElementById('searchInput');
        const tableBody = document.getElementById('ticket-table').getElementsByTagName('tbody')[0];

    </script>
    <script src="{% static 'scripts/tickets_list/search_tickets.js' %}"></script>
    <script>
        searchInput.addEventListener('input', filterTable);
    </script>
{% endblock is_rady %}

src/EoManager/templates/supervisor/windows_list.html
{% extends "supervisor/base.html" %}

{% block content %}
    <h1>Список окон</h1>
    <div id="windows-list">
        <p>Таблица со списком талонов</p>
    </div>
{% endblock content %}